using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CapaEntidad
{
    public class ClienteDTO
    {
        public int IdCliente { get; set; }
        public string NombreCliente { get; set; }
        public string Correo { get; set; }
        public string Telefono { get; set; }
        public string FechaIngreso { get; set; }


    }
}
